# Change these first
owner: hamboneza # Your GitHub organization or username, where this repository lives
repo: caffeine # The name of this repository

sites:
  - name: ZA - MAIL SERVER
    url: https://www.google.com
    maxResponseTime: 5000
  - name: Wikipedia
    url: https://en.wikipedia.org
    maxResponseTime: 4000
  - name: Hacker News
    url: https://news.ycombinator.com
    maxResponseTime: 3000
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    maxResponseTime: 10

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /caffeine
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Caffeine - An Uptime Monitor
  introTitle: "**Caffeine** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is where you can find very pretty graphs and stats about our server clusters and workers. Ask us for your site status page and we will whip one up for you.
  navbar:
    - title: Common Services
      href: /
    - title: Data Centers
      href: /
    - title: Mail
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
