# Change these first
owner: hamboneza # Your GitHub organization or username, where this repository lives
repo: caffeine # The name of this repository

sites:
  - name: Postfix
    url: https://www.google.com
    maxResponseTime: 500
  - name: Dovecot
    url: https://en.wikipedia.org
    maxResponseTime: 400
  - name: IMAP
    url: https://news.ycombinator.com
    maxResponseTime: 300
  - name: ClamAV
    url: https://thissitedoesnotexist.koj.co
    maxResponseTime: 10
  - name: Nginx Clusters
    url: https://www.google.com
    maxResponseTime: 500
  - name: MySQL Servers
    url: https://en.wikipedia.org
    maxResponseTime: 400
  - name: PostgreSQL
    url: https://news.ycombinator.com
    maxResponseTime: 300

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: night
  baseUrl: /caffeine
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Caffeine - An Uptime Monitor
  introTitle: "**Caffeine** keeps us going, so your application keeps on ticking."
  introMessage: Ask us for your very own site status page and we will whip one up for you.
  navbar:
    - title: Workers
      href: /
    - title: Applications
      href: /
    - title: APIs
      href: /
    - title: Databases
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
